version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npx run tsc
      - run: npm run test
# Orchestrate our job run sequence
workflows:
    version: 2.1
    build_and_test:
        jobs:
        - build